# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: packaging/sdaps.spec
upstream_project_url: https://github.com/sdaps/sdaps

# add or remove files that should be synced
files_to_sync:
    - src: packaging/sdaps.spec
      dest: sdaps.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: sdaps
# downstream (Fedora) RPM package name
downstream_package_name: sdaps

# Running ./setup.py sdist requires distutils-extra and some pkgconfig dependencies
srpm_build_deps:
 - python3-distutils-extra
 - python3-cairo-devel

actions:
  post-upstream-clone:
   - "git submodule init"
   - "git submodule update"
  create-archive:
   - python3 ./setup.py sdist
   - sh -c 'mv "dist/sdaps-$(python3 ./setup.py --version).tar.gz" packaging'
   - sh -c 'echo "packaging/sdaps-$(python3 ./setup.py --version).tar.gz"'

jobs:
  - job: copr_build
    trigger: pull_request
    metadata:
      targets:
        - fedora-development-x86_64
        - fedora-development-i386
        - fedora-development-aarch64
        - fedora-development-ppc64le
        - fedora-development-s390x
        - fedora-development-armhfp


