# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: packaging/sdaps.spec
upstream_project_url: https://github.com/sdaps/sdaps
upstream_tag_template: v{version}

# add or remove files that should be synced
files_to_sync:
    - src: packaging/sdaps.spec
      dest: sdaps.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: sdaps
# downstream (Fedora) RPM package name
downstream_package_name: sdaps

srpm_build_deps:
 - meson
 - gcc
 - python3-cairo-devel
 - pkgconfig(libtiff-4)

actions:
  post-upstream-clone:
   - "git submodule init"
   - "git submodule update"
  create-archive:
   - meson setup tmp/dist
   - meson dist -C tmp/dist --no-tests --allow-dirty
   - sh -ec 'mv tmp/dist/meson-dist/sdaps-*.tar.xz packaging/; ls packaging/sdaps-*.tar.xz'

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
     - fedora-development-x86_64
     - fedora-development-i386
     - fedora-development-aarch64
     - fedora-development-ppc64le
     - fedora-development-s390x
     - fedora-development-armhfp

  - job: copr_build
    trigger: release
    owner: benzea
    project: sdaps
    list_on_homepage: true
    targets:
     - fedora-all-x86_64
     - fedora-all-i386
     - fedora-all-aarch64
     - fedora-all-ppc64le
     - fedora-all-s390x
     - fedora-all-armhfp
